Update draw_keymaps.yaml

diff --git a/.github/workflows/draw_keymaps.yaml b/.github/workflows/draw_keymaps.yaml
--- a/.github/workflows/draw_keymaps.yaml
+++ b/.github/workflows/draw_keymaps.yaml
@@ -4,6 +4,7 @@ name: Draw ZMK keymaps
 
 env:
   FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
+
 on:
   workflow_call:
     inputs:
@@ -18,8 +19,8 @@ on:
         required: false
         type: string
       west_config_path:
-        description: "Path to the folder containing west.yml, e.g. `config`. If specified, west will be initialized to fetch modules defined in west.yml"
-        default: ""
+        description: "Path to the folder containing west.yml, e.g. `config`. Set to empty to skip fetching modules from west.yml"
+        default: "config"
         required: false
         type: string
       output_folder:
@@ -34,11 +35,16 @@ on:
         type: string
       parse_args:
         description: "Map of keyboard names to extra `keymap parse` args, e.g. `corne:'--layer-names Def Lwr Rse Fun'`"
-        default: "charybdis: '-b keymap-drawer/charybdis.yaml'"
+        default: ""
         required: false
         type: string
       draw_args:
         description: "Map of keyboard names to extra `keymap draw` args, e.g. `corne:'-k corne_rotated -l LAYOUT_split_3x5_3'`"
+        default: ""
+        required: false
+        type: string
+      extra_keymap_yaml:
+        description: "Map of keyboard names to extra keymap YAMLs to be passed to `keymap draw` after the parsed one"
         default: ""
         required: false
         type: string
@@ -48,33 +54,43 @@ on:
         required: false
         type: string
       amend_commit:
-        description: "Whether to amend the last commit instead of creating a new one. Make sure you understand the implications of rewriting the branch history if you use this option!"
+        description: "Whether to amend the last commit instead of creating a new one"
         default: true
         required: false
         type: boolean
       install_branch:
-        description: "Install keymap-drawer from a git branch, use empty for pypi release (default)"
+        description: "Install keymap-drawer from a git branch, use empty to install from PyPI"
         default: ""
         required: false
         type: string
       install_repo:
-        description: "Install keymap-drawer from a different git remote, primarily for testing changes using a keymap-drawer fork. Ignored if `install_branch` is unset/empty."
+        description: "Install keymap-drawer from a different git remote"
         default: "https://github.com/caksoylar/keymap-drawer.git"
         required: false
         type: string
+      install_version:
+        description: "Install keymap-drawer from PyPI using the specified version, use empty for latest"
+        default: ""
+        required: false
+        type: string
       destination:
-        description: "Add the output files to a commit, as artifacts or both, values: `commit`, `artifact`, `both`"
+        description: "Add the output files to a commit, as artifacts or both"
         default: "commit"
         required: false
         type: string
       artifact_name:
-        description: "Name of the produced artifact containing SVG and YAML outputs. Ignored if `destination` is `commit`."
+        description: "Name of the produced artifact containing SVG and YAML outputs"
         default: "keymap_layouts"
         required: false
         type: string
       fail_on_error:
         description: "Fail the action if an error occurs during parse/draw"
         default: true
+        required: false
+        type: boolean
+      debug_mode:
+        description: "Enable debug mode"
+        default: false
         required: false
         type: boolean
     outputs:
@@ -91,108 +107,160 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
         with:
-          # So the reference to the parent commit is available when amending
-          # See:
-          # - https://github.com/stefanzweifel/git-auto-commit-action#using---amend-and---no-edit-as-commit-options
-          # - https://github.com/stefanzweifel/git-auto-commit-action/issues/159#issuecomment-845347950
-          # - https://github.com/actions/checkout
           fetch-depth: ${{ (inputs.amend_commit == true && 2) || 1 }}
           submodules: recursive
 
       - name: Install keymap-drawer (pypi)
         if: inputs.install_branch == ''
-        run: python3 -m pip install keymap-drawer
+        run: |
+          [ -n "${{ inputs.install_version }}" ] && version="==${{ inputs.install_version }}" || version=""
+          pipx install "keymap-drawer$version"
 
       - name: Install keymap-drawer (git)
         if: inputs.install_branch != ''
-        run: python3 -m pip install "git+${{ inputs.install_repo }}@${{ inputs.install_branch }}"
+        run: pipx install "git+${{ inputs.install_repo }}@${{ inputs.install_branch }}"
 
       - name: Install west
         if: inputs.west_config_path != ''
-        run: python3 -m pip install west
+        run: pipx install west
 
-      - name: Cache west modules
-        if: inputs.west_config_path != ''
-        uses: actions/cache@v4
-        continue-on-error: true
-        env:
-          cache_name: cache-zephyr-3.5.0-modules
-        with:
-          path: |
-            modules/
-            tools/
-            zephyr/
-            bootloader/
-            zmk/
-          key: ${{ runner.os }}-build-${{ env.cache_name }}-${{ hashFiles('**/west.yml', '**/build.yaml') }}
-          restore-keys: |
-            ${{ runner.os }}-build-${{ env.cache_name }}-
-            ${{ runner.os }}-build-
-            ${{ runner.os }}-
-
-      - name: West Init
+      - name: Fetch west modules
         if: inputs.west_config_path != ''
         run: |
-          ls -Rhl $GITHUB_WORKSPACE
           west init -l ${{ inputs.west_config_path }}
+          west config --local manifest.project-filter "-zmk,-zephyr"
+          west update --fetch-opt=--filter=tree:0
 
-      - name: West Update
-        if: inputs.west_config_path != ''
-        run: west update
-
-      - name: Parse keymaps
-        run: |
-          shopt -s globstar nullglob
-          [[ -f "${{ inputs.config_path }}" ]] && config_arg=(--config "${{ inputs.config_path }}") || config_arg=()
-          for keymap in ${{ inputs.keymap_patterns }}; do
-            name="$(basename "${keymap}" .keymap)"
-            args="$(echo "${{ inputs.parse_args }}" | yq -r ".\"${name}\" // empty")"
-            keymap parse -c "${config_arg[@]}" ${args} "${keymap}" > "${{ inputs.output_folder }}/${name}.yaml"
-          done
+      - name: Draw keymaps
+        id: draw
+        continue-on-error: ${{ !inputs.fail_on_error }}
         shell: bash
-
-      - name: Draw SVGs
         run: |
-          shopt -s globstar nullglob
-          for yaml in "${{ inputs.output_folder }}"/*.yaml; do
-            name="$(basename "${yaml}" .yaml)"
-            json=""
-            if [[ -f "${{ inputs.json_path }}/${name}.json" ]]; then
-              json="-j ${{ inputs.json_path }}/${name}.json"
+          [ "${{ inputs.debug_mode }}" == "true" ] && set -x
+
+          get_args() {
+            local mapping="$1"
+            local keyboard="$2"
+            local output=()
+            eval set -- "$mapping"
+            for arg; do
+              local key=${arg%%:*}
+              local val=${arg#*:}
+              if [ "$key" = "$keyboard" ]; then
+                output+=("$val")
+                break
+              fi
+            done
+            echo "${output[@]}"
+          }
+
+          check_for_layout_args() {
+            local args=("$@")
+            for val in "-j" "--qmk-info-json" "-k" "--qmk-keyboard" "-z" "--zmk-keyboard" "-d" "--dts-layout" "--ortho-layout" "-n" "--cols-thumbs-notation"; do
+              for item in "${args[@]}"; do
+                if [ "$val" = "$item" ]; then
+                  return 0
+                fi
+              done
+            done
+            return 1
+          }
+
+          shopt -s nullglob extglob
+          artifacts=()
+          error_occurred=0
+          mkdir -p "${{ inputs.output_folder }}"
+
+          config_path="${{ inputs.config_path }}"
+          [ -e "$config_path" ] && config_arg=(-c "$config_path") || config_arg=()
+          echo "INFO: using config args:" "${config_arg[@]}"
+
+          [ "${{ inputs.debug_mode }}" == "true" ] && debug_arg="-d" || debug_arg=""
+
+          for keymap_file in ${{ inputs.keymap_patterns }}; do
+            keyboard=$(basename -s .keymap "$keymap_file")
+            echo "INFO: drawing for $keyboard"
+
+            IFS=" " read -r -a parse_args <<< "$(get_args "${{ inputs.parse_args }}" "$keyboard")"
+            echo "INFO: got extra parse args:" "${parse_args[@]}"
+
+            IFS=" " read -r -a draw_args <<< "$(get_args "${{ inputs.draw_args }}" "$keyboard")"
+            echo "INFO: got extra draw args:" "${draw_args[@]}"
+
+            IFS=" " read -r -a extra_keymap_yaml <<< "$(get_args "${{ inputs.extra_keymap_yaml }}" "$keyboard")"
+            echo "INFO: got extra keymap YAML args:" "${extra_keymap_yaml[@]}"
+
+            json_path="${{ inputs.json_path }}"
+            if check_for_layout_args "${draw_args[@]}"; then
+              echo "INFO: found layout specifiers in draw args"
+            elif [ -n "$json_path" ] && [ -f "$json_path/${keyboard}.json" ]; then
+              echo "INFO: found $json_path/${keyboard}.json"
+              draw_args+=(-j "$json_path/${keyboard}.json")
+            else
+              dts_candidates=({,*/}boards/*/*/${keyboard}-layout{,s}.dtsi)
+              if [ ${#dts_candidates[@]} -gt 0 ]; then
+                echo "INFO: found ${dts_candidates[0]}"
+                draw_args+=(-d "${dts_candidates[0]}")
+              fi
             fi
-            args="$(echo "${{ inputs.draw_args }}" | yq -r ".\"${name}\" // empty")"
-            keymap draw ${json} ${args} "${yaml}" > "${{ inputs.output_folder }}/${name}.svg"
-          done
-        shell: bash
 
-      - name: Archive drawings
-        if: inputs.destination != 'commit'
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ inputs.artifact_name }}
-          path: ${{ inputs.output_folder }}
+            tmp_yaml=$(mktemp)
+            tmp_svg=$(mktemp)
+
+            if keymap $debug_arg "${config_arg[@]}" parse -z "$keymap_file" "${parse_args[@]}" >"$tmp_yaml"; then
+              mv "$tmp_yaml" "${{ inputs.output_folder }}/$keyboard.yaml"
+              artifacts+=("${{ inputs.output_folder }}/$keyboard.yaml")
+            else
+              echo "ERROR: parsing failed for $keyboard!"
+              error_occurred=1
+              continue
+            fi
+
+            if keymap $debug_arg "${config_arg[@]}" draw "${{ inputs.output_folder }}/$keyboard.yaml" "${extra_keymap_yaml[@]}" "${draw_args[@]}" >"$tmp_svg"; then
+              mv "$tmp_svg" "${{ inputs.output_folder }}/$keyboard.svg"
+              artifacts+=("${{ inputs.output_folder }}/$keyboard.svg")
+            else
+              echo "ERROR: drawing failed for $keyboard!"
+              error_occurred=1
+            fi
+          done
+
+          joined_artifacts=$(printf '"%s", ' "${artifacts[@]}")
+          printf 'artifacts=[%s]\n' "${joined_artifacts%, }" >> "$GITHUB_OUTPUT"
+
+          if [ $error_occurred -eq 1 ]; then
+            exit 1
+          fi
 
       - name: Get last commit message
-        if: inputs.destination != 'artifact' && inputs.amend_commit == true
         id: last_commit_message
+        if: inputs.amend_commit == true && (inputs.destination == 'commit' || inputs.destination == 'both')
         run: |
-          echo "msg<<EOF" >> "$GITHUB_OUTPUT"
-          git log -1 --pretty=%B >> "$GITHUB_OUTPUT"
-          echo "EOF" >> "$GITHUB_OUTPUT"
+          echo "msg=$(git log -1 --pretty=%s)" >> "$GITHUB_OUTPUT"
 
-      - name: Commit SVGs
-        if: inputs.destination != 'artifact'
+      - name: Commit updated images
+        if: inputs.destination == 'commit' || inputs.destination == 'both'
         uses: stefanzweifel/git-auto-commit-action@v5
         with:
-          # The previous commit message is re-used if the previous commit is amended instead of creating a new one when desired
-          # See:
-          # - https://github.com/stefanzweifel/git-auto-commit-action#using---amend-and---no-edit-as-commit-options
-          # - https://github.com/stefanzweifel/git-auto-commit-action/issues/159#issuecomment-845347950
-          # - https://github.com/actions/checkout
-          commit_message: "${{ (inputs.amend_commit == true && steps.last_commit_message.outputs.msg) || inputs.commit_message }}"
+          file_pattern: '${{ inputs.output_folder }}/*.svg ${{ inputs.output_folder }}/*.yaml'
+          commit_message: '${{ (inputs.amend_commit == true && steps.last_commit_message.outputs.msg) || inputs.commit_message }}'
           commit_options: "${{ (inputs.amend_commit == true && '--amend --no-edit') || '' }}"
           push_options: "${{ (inputs.amend_commit == true && '--force-with-lease') || '' }}"
           skip_fetch: ${{ inputs.amend_commit == true }}
 
       - name: Artifact upload
         id: artifact-upload-step
+        if: inputs.destination == 'artifact' || inputs.destination == 'both'
+        uses: actions/upload-artifact@v4
+        with:
+          name: '${{ inputs.artifact_name }}'
+          path: |
+            ${{ join(fromJSON(steps.draw.outputs.artifacts), ' ') }}
+
+      - name: Check job success
+        if: ${{ !inputs.fail_on_error }}
+        run: |
+          if [ "${{ steps.draw.outcome }}" == "failure" ]; then
+            echo "The draw step failed for some keymaps, please check the logs of that step above!"
+            exit 1
+          fi
